#!groovy

// Generated by IBM TransformationAdvisor
// Sat Jan 26 18:39:20 UTC 2019

@Library('MicroserviceBuilder') _
microserviceBuilderPipeline {
    image = 'daytraderee6'
    mvnCommands = '--version'
    test='false'
}